const GENERATION = {
  FETCH: "GENERATION_FETCH",
  FETCH_ERROR: "GENERATION_ERROR",
  FETCH_SUCCESS: "GENERATION_SUCCESS",
};

const DRAGON = {
  FETCH: "FETCH",
  FETCH_ERROR: "FETCH_ERROR",
  FETCH_SUCCESS: "FETCH_SUCCESS",
};

export { GENERATION, DRAGON };
